apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dummy-webapp-development
  namespace: argocd
spec:
  project: webapp
  source:
    repoURL: https://github.com/noizy-sthlm/dummyWeb-ArgoCDk8s.git
    targetRevision: dev
    path: manifests/
  destination:
    server: https://kubernetes.default.svc
    namespace: dummy-webapp-development
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
