   apiVersion: argoproj.io/v1alpha1
   kind: Application
   metadata:
     name: multi-branch-pipeline-dev
     namespace: argocd
   spec:
     project: default
     source:
       repoURL: https://github.com/noizy-sthlm/tutorial-ArgoCd-multi-branch-pipeline/
       targetRevision: dev
       path: manifests/
     destination:
       server: https://kubernetes.default.svc
       namespace: default
     syncPolicy:
       automated:
         prune: true
         selfHeal: true
